# Cargo.toml

[package]
name = "net-serial-console"
version = "0.3.1"
authors = ["Sami J. Mäkinen <sjm@iki.fi>"]
description = "Serial console tcp server/multiplexer and web client"
repository = "https://github.com/sjm42/net-serial-console-rs"
readme = "README.md"
keywords = ["serial", "console", "multiplex"]
license = "MIT OR Apache-2.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1"
chrono = "0.4"
env_logger = "0.9"
hyper = { version = "0.14", features = ["full"] }
log = "0.4"
once_cell = "1.8"
parking_lot = "0.11"
sailfish = "0.3"
structopt = "0.3"
tokio = { version = "1.11", features = ["full"] }
tokio-serial = "5.4"
tokio-util = { version = "0.6", features = ["full"] }
tokio-tungstenite = "*"

[build-dependencies]
build-data = "0.1"

[profile.release]
lto = true
opt-level = 3 #default
# opt-level = 'z'  # Optimize for size.

# EOF
